#! /bin/bash -e

BASE_DIR_PATH="${BASE_DIR_PATH}"

INTERNAL_NIC_NAME=ens192
EXTERNAL_NIC_NAME=ens160

OPENSHIFT_CLIENT_LINUX_DOWNLOAD_URL="https://mirror.openshift.com/pub/openshift-v4/clients/ocp/4.5.6/openshift-client-linux-4.5.6.tar.gz"
OPENSHIFT_INSTALL_LINUX_DOWNLOAD_URL="https://mirror.openshift.com/pub/openshift-v4/clients/ocp/4.5.6/openshift-install-linux-4.5.6.tar.gz"


OPENSHIFT_CLIENT_LINUX_TAR_FILE_NAME="openshift-client-linux.tar.gz"
OPENSHIFT_INSTALL_LINUX_TAR_FILE_NAME="openshift-install-linux.tar.gz"


wget -c ${OPENSHIFT_CLIENT_LINUX_DOWNLOAD_URL} -o ${OPENSHIFT_CLIENT_LINUX_TAR_FILE_NAME}
wget -c ${OPENSHIFT_INSTALL_LINUX_DOWNLOAD_URL} -o ${OPENSHIFT_INSTALL_LINUX_TAR_FILE_NAME}


# Extract Client tools and copy them to /usr/local/bin
tar xvf ${OPENSHIFT_CLIENT_LINUX_TAR_FILE_NAME}
mv oc kubectl /usr/local/bin

# Confirm Client Tools are working
echo $(oc version)
echo $(kubectl version)

# Extract the OpenShift Installer
tar xvf ${OPENSHIFT_INSTALL_LINUX_TAR_FILE_NAME}

# ${RHCOS_RAW_FILE_NAME}

cat <<EOT >> ~/.vimrc
syntax on
set nu et ai sts=0 ts=2 sw=2 list hls
EOT

echo "export OC_EDITOR=\"vim\"" >> ~/.bash_profile
echo "export KUBE_EDITOR=\"vim\"" >> ~/.bash_profile
source ~/.bash_profile


# cat <<EOT >> /etc/resolv.conf
# # Generated by NetworkManager
# search localdomain ocp.lan
# nameserver 172.16.218.2
# nameserver 127.0.0.1
# EOT

nmcli con mod ens192 ipv4.addresses 192.168.22.10/24
# nmcli con mod ens192 ipv4.gateway 192.168.2.1
nmcli con mod ens192 ipv4.dns "127.0.0.1"
nmcli con mod ens192 ipv4.method manual
nmcli con mod ens192 ipv4.dns-search "ocp.lan"
systemctl restart NetworkManager

nmcli connection modify ens160 connection.zone internal
nmcli connection modify ens192 connection.zone external

firewall-cmd --get-active-zones
firewall-cmd --zone=external --add-masquerade --permanent
firewall-cmd --zone=internal --add-masquerade --permanent
firewall-cmd --reload

echo $(firewall-cmd --list-all --zone=internal)
echo $(firewall-cmd --list-all --zone=external)
echo $(cat /proc/sys/net/ipv4/ip_forward)